- name: create prometheus group
  group: name="{{groupId}}"
  become: true

- name: create user
  user: 
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin user"
    createhome: no
    state: present

- name: install prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{prom_version}}/prometheus-{{prom_version}}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes


- name: copy promethenus directory to /usr/local/bin folder
  copy: 
    src: "/tmp/prometheus-{{prom_version}}.linux-amd64/prometheus"
    dest: "/usr/local/bin/"
    owner: "{{userId}}"
    group: "{{groupId}}"
    directory_mode:
    remote_src: yes
    mode: 0755

- name: copy promethenus directory to /usr/local/bin folder
  copy:
    src: "/tmp/prometheus-{{prom_version}}.linux-amd64/prometheus.yml"
    dest: "/usr/local/bin/"
    owner: "{{userId}}"
    group: "{{groupId}}"
    directory_mode:
    remote_src: yes
    mode: 0755

- name: delete tmp folder
  file:
    path: "/tmp/prometheus-{{prom_version}}.linux-amd64"
    state: absent

- name: create directory
  file:
    path: "/data/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: create directory
  file:
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: config file
  template:
    src: prometheus.conf.j2
    dest: /usr/local/bin/prometheus.yml

- name: copy init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload


- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: check prometheus accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
