---
# handlers file for prometheus
- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload
  become: true
